### ISSUE TITLE
AbstractPluginManager accepts null, then throws E_USER_DEPRECATED

### ISSUE THREAD

**Issue by nataniel** [zendframework/zend-servicemanager#100]
This code should not be executed if configInstanceOrParentLocator  is null:

`if (! $configInstanceOrParentLocator instanceof ContainerInterface) {`

Currently it throws E_USER_DEPRECATED for no reason.

**Comment by weierophinney** [comment]
It throws an E_USER_DEPRECATED because the usage of a `Config` instance in the constructor is *deprecated* as of v3; the first argument is expected to be a parent locator instance. We have it accept the `Config` instance for now to allow developers a chance to migrate, and deprecation notices such as these help you determine what you may need to do in your code to upgrade.

**Comment by nataniel** [comment]
I guess you didn't read what I have written. It throws E_USER_DEPRECATED when using `null`, not the `Config` instance. Is it deprecated to pass null to the constructor?

**Comment by weierophinney** [comment]
> Is it deprecated to pass null to the constructor?

Yes. Starting with v3, `AbstractPluginManager` instances expect the parent container as a constructor argument.
