### ISSUE TITLE
is it possible that 2.7.5 contains BC break?

### ISSUE THREAD

**Issue by svycka** [zendframework/zend-servicemanager#109]
in https://github.com/bushbaby/BsbFlysystem module everything works with <=2.7.4 then I changed zend-sericemanager from 2.7.4 to 2.7.5 in composer and run composer update:
```
Updating dependencies (including require-dev)
  - Removing zendframework/zend-eventmanager (2.6.3)
  - Installing zendframework/zend-eventmanager (3.0.1)
    Loading from cache

  - Removing zendframework/zend-servicemanager (2.7.4)
  - Installing zendframework/zend-servicemanager (2.7.5)
    Loading from cache

  - Removing zendframework/zend-cache (2.5.3)
  - Installing zendframework/zend-cache (2.6.1)
    Loading from cache

  - Removing zendframework/zend-log (2.6.0)
  - Installing zendframework/zend-log (2.7.1)
    Loading from cache

  - Installing psr/http-message (1.0)
    Loading from cache

  - Installing zendframework/zend-diactoros (1.3.5)
    Loading from cache

  - Installing zendframework/zend-escaper (2.5.1)
    Loading from cache

  - Installing zendframework/zend-uri (2.5.2)
    Loading from cache

  - Installing zendframework/zend-http (2.5.4)
    Loading from cache

  - Installing zendframework/zend-psr7bridge (0.2.1)
    Loading from cache

  - Removing zendframework/zend-mvc (2.6.3)
  - Installing zendframework/zend-mvc (2.7.3)
    Loading from cache

Writing lock file
Generating autoload files
```
after only this change tests fails.
because travis did not work as expected I copy pasted phpunit output here 
https://github.com/bushbaby/BsbFlysystem/pull/25

ping @weierophinney

**Comment by weierophinney** [comment]
Looking at the output and the specific tests and code, it looks like you're getting a null value for the given plugin manager after pulling it from the container; this is then being passed to the factory, which is when the error occurs.

I'll need you to do some more tracking to figure out why the null values are being returned, as I'm not familiar enough with the code in that module.

**Comment by svycka** [comment]
@weierophinney ok I have tracked down it may not be related with service manager but with zend-mvc here https://github.com/zendframework/zend-mvc/blob/release-2.6.3/src/Service/ServiceManagerConfig.php#L114 service locator is set here in zend-mvc 2.6.3 but in zend-mvc 2.7.0 this initializer is refactored and no longer set the service locator 
now it look like this:
https://github.com/zendframework/zend-mvc/blob/release-2.7.3/src/Service/ServiceManagerConfig.php#L131-L171
I am not sure how this should work here maybe you can explain? what changed?

again: the issue is not with zend-servicemanager I guess, but with zend-mvc >=2.7.0 unless I am wrong :D should we move this to zend-mvc?

**Comment by svycka** [comment]
I just inverted if in the initializer like this
```
ServiceLocatorAwareInitializer' => function ($first, $second) {
    if (!$first instanceof ContainerInterface) {
    // ^ added '!' here
        $container = $first;
        $instance = $second;
    } else {
        $container = $second;
        $instance = $first;
    }
//....
```
Noticed that both of them implement ContainerInterface so just tested and now everything works as expected at least tests pass and also works in my project, but I have no idea what I just did so @weierophinney can you explain or fix this?

**Comment by weierophinney** [comment]
That "fix" would break any other type of `ServiceLocatorAware` class!

I figured out what the issue is, and it's definitely an edge case. What's happening is that you're relying on using the initializer to inject your *plugin managers*. This causes a unique situation with the initializer, because *both* arguments are implementations of `ContainerInterface`, and, as such, the first conditional was always evaluating true, regardless of zend-servicemanager version. In this situation, the `$instance` evaluates to the SM instance under v2, determines it's not SM-Aware, and moves on without doing anything.

This works fine for the plugin managers that have factories in zend-mvc, as the factories were rewritten to inject the service manager instance during instantiation of the plugin manager, which means that the current initializer behavior of  is not a problem for them, as the SM instance is already injected.

In your situation, however, it breaks under v2, because you're not injecting the SM instance in your abstract factory, and thus the fact that the initializer mis-detects the plugin manager instance as the SM instance leads to a no-op.

There are two situations, then, to address:

- I'll create a patch for a 2.7.6 release of zend-mvc to address the behavior. This patch will also test to see if an SM instance is already injected, and, if so, do nothing.
- *You* should update your abstract factory to inject the SM instance. This will be necessary anyways to make your code forwards compatible with zend-servicemanager v3, as plugin managers in that version *require* that you pass the parent locator to the constructor.

**Comment by svycka** [comment]
that's not my module just run into those problems while updating, but I will think about creating PR for them.

**Comment by basz** [comment]
> You should update your abstract factory to inject the SM instance. This will be necessary anyways to make your code forwards compatible with zend-servicemanager v3, as plugin managers in that version require that you pass the parent locator to the constructor.

That would be me :-) @svycka a PR would be great!
