### ISSUE TITLE
Classes conflicts with zend-servicemanager-di

### ISSUE THREAD

**Issue by remicollet** [zendframework/zend-servicemanager#125]
See https://github.com/zendframework/zend-mvc/commit/65b6f01536efc34f2fbd08a85caf73b692d1cd5c

So, installing zf2 (only 2.x components) you have both zend-servicemanager 2.7 and zend-servicemanager-di 1.0, both providing the same classes.

perhaps
- zend-servicemanager should drop these classes and requires zend-servicemanager-di 
or
- zend-mvc should not requires zend-servicemanager-di (which should then be required by zend-servicemanager > 3)

**Comment by weierophinney** [comment]
@remicollet I have several comments:

- First, zend-servicemanager-di is tested against both zend-servicemanager v2 and v3, and works correctly against both versions.
- Second, the code in zend-servicemanager-di is a verbatim copy from zend-servicemanager v2 versions, with the addition of factories that were originally in the zend-mvc package. There are no code changes in the actual service manager &lt;=&gt; DI integration pieces. Further, there have been no meaningful changes to them for years, and no plans to make further changes going forward, as they are not recommended by us (the functionality is a great way to shoot yourself in the foot with regards to dependency resolution and performance). As such, *it doesn't matter which package the various duplicate classes resolve to, as they are identical, and will be for the foreseeable future*.

The original plan was to have the code only be for users of zend-servicemanager v3 who relied on the code. However, when we realized the above, we realized we were also providing a migration path from v2 to v3 for both zend-servicemanager and zend-mvc.

I completely recognize the potential risk in determining which class gets loaded; however, the risk is mitigated by the fact that the functionality is identical between the packages. Any new changes will occur in zend-servicemanager-di, and we can backport them to this component *if needed* (i.e., if we are still seeing significant zend-mvc v2 usage). If that becomes onerous or problematic, we'll create another zend-servicemanager v2 minor release that removes the zend-servicemanager-di functionality, and adds a dependency on zend-servicemanager-di itself. Right now, it *just works*.

**Comment by remicollet** [comment]
Sounds terrible :(

**Comment by remicollet** [comment]
More: 
```
$ composer dumpautoload --optimize
Generating optimized autoload files
Warning: Ambiguous class resolution, "Zend\ServiceManager\Di\DiServiceInitializer" was found in both "/tmp/foo/vendor/zendframework/zend-servicemanager-di/src/DiServiceInitializer.php" and "/tmp/foo/vendor/zendframework/zend-servicemanager/src/Di/DiServiceInitializer.php", the first will be used.
Warning: Ambiguous class resolution, "Zend\ServiceManager\Di\DiServiceFactory" was found in both "/tmp/foo/vendor/zendframework/zend-servicemanager-di/src/DiServiceFactory.php" and "/tmp/foo/vendor/zendframework/zend-servicemanager/src/Di/DiServiceFactory.php", the first will be used.
Warning: Ambiguous class resolution, "Zend\ServiceManager\Di\DiInstanceManagerProxy" was found in both "/tmp/foo/vendor/zendframework/zend-servicemanager-di/src/DiInstanceManagerProxy.php" and "/tmp/foo/vendor/zendframework/zend-servicemanager/src/Di/DiInstanceManagerProxy.php", the first will be used.
Warning: Ambiguous class resolution, "Zend\ServiceManager\Di\DiAbstractServiceFactory" was found in both "/tmp/foo/vendor/zendframework/zend-servicemanager-di/src/DiAbstractServiceFactory.php" and "/tmp/foo/vendor/zendframework/zend-servicemanager/src/Di/DiAbstractServiceFactory.php", the first will be used.

```

And, of course, this make impossible to create a downstream distribution into a single PSR-0 tree.

**Comment by remicollet** [comment]
Trying to run servicemanager test suite, using servicemanager-di

      PHP Fatal error:  Call to undefined method Zend\ServiceManager\Di\DiServiceInitializer::initialize() in /builddir/build/BUILD/zend-servicemanager-a6db4d13b9141fccce5dcb553df0295d6ad7d477/test/Di/DiServiceInitializerTest.php

**Comment by weierophinney** [comment]
@remicollet I'm not sure I understand what you mean by "trying to run servicemanager test suite, using servicemanager-di" - can you tell me exactly the steps to reproduce?

The more serious issue to me is the `composer dumpautoload --optimize` one, and I do want to resolve that.

The problem I'm looking at, however, is this:

- We added zend-servicemanager-di as a dep to zend-mvc v2 as it was tested against both major versions of zend-servicemanager, and allows zend-mvc v2 to be used with either version. Prior to that change, zend-mvc v2 users who updated to zend-servicemanager v3 had their code breaking in unexpected and hard to debug ways if they were using the servicemanager/DI integration (as that functionality is removed from zend-servicemanager v3).
- If we do a new zend-servicemanager v2 release that removes the `Zend\ServiceManager\Di` classes and then adds zend-servicemanager-di as a dependency, we run into the same problem for zend-mvc v2 users (as zend-servicemanager v3 does not have that dependency, and we will not be introducing it for that version). In other words: this "solution" puts us exactly back where we were before the changes.
- Unfortunately, there is no way in Composer to create conditional dependencies; we cannot say, "if using version X of package Y, install package Z; otherwise, do not."

The only solution I can think of is:

- Mark zend-servicemanager-di as "conflicts with zend-servicemanager ^2.0".
- Remove the dependency in zend-mvc v2 and restore the removed code (with fixes as made in zend-servicemanager-di 1.0.1).
- Make a suggestion in zend-mvc v2 to install zend-servicemanager-di if using zend-servicemanager v3, indicating that if you use the zend-di &lt;-&gt; zend-servicemanager integration it will be broken otherwise.

This doesn't solve the original problem, but at least gives some information at installation time.

Do you have any constructive suggestions to counter with?

**Comment by weierophinney** [comment]
Fixed with zend-mvc 2.7.10 and zend-servicemanager-di 1.1.0.

**Comment by remicollet** [comment]
Indeed, seems the safest way.

Thanks a lot.

**Comment by Ocramius** [comment]
Thanks for the quick fix! This just got reported on IRC too, and the resolution should indeed help :-)
