### ISSUE TITLE
Why shared large do not work by base name of class?

### ISSUE THREAD

**Issue by bupy7** [zendframework/zend-servicemanager#145]
In ZF2 shared worked both base name and alias name of class. Now (ZF3) shared work only by specified name of class or alias in config. Example, test ended with a error: [test](https://travis-ci.org/bupy7/zf-form/jobs/155400402#L358) . In ZF2 it worked: [old test](https://travis-ci.org/bupy7/zf-form/jobs/152058623).

My config following:

```php
return [
    'service_manager' => [
        'factories' => [
            FormBuilder::class => FormBuilderFactory::class,
        ],
        'shared' => [
            FormBuilder::class => false,
        ],
        'aliases' => [
            'Bupy7\Form\FormBuilder' => FormBuilder::class,
        ],
    ],
    'view_helpers' => [
        'factories' => [
            FormBuilderHelper::class => FormBuilderHelperFactory::class,
        ],
        'shared' => [
            FormBuilderHelper::class => false,
        ],
        'aliases' => [
            'formBuilder' => FormBuilderHelper::class,
        ],
    ],
];
```

If to change to:

```php
return [
    'service_manager' => [
        'factories' => [
            FormBuilder::class => FormBuilderFactory::class,
        ],
        'shared' => [
            FormBuilder::class => false,
            'Bupy7\Form\FormBuilder' => false,
        ],
        'aliases' => [
            'Bupy7\Form\FormBuilder' => FormBuilder::class,
        ],
    ],
    'view_helpers' => [
        'factories' => [
            FormBuilderHelper::class => FormBuilderHelperFactory::class,
        ],
        'shared' => [
            FormBuilderHelper::class => false,
            'formBuilder' => false,
        ],
        'aliases' => [
            'formBuilder' => FormBuilderHelper::class,
        ],
    ],
];
```

all work. Both name of class and alias of class.

Is it bug or no?

**Comment by weierophinney** [comment]
There were a number of changes made with regards to aliases for version 3, mostly around consistency and performance.

We do have code that will check that the requestedName is shared, and, if so cache it as such. However, the bit to consider is that *services are shared by default*, which means that if you:

- have a named service mapped to a factory
- which you mark as not shared
- but then have an alias that also maps to that named service
- but do not override the shared settings for the alias
- then the aliased service *is shared*

This is by design; aliases inherit the global settings, not the settings of the service they inherit from. This allows you to, for instances, mark an aliased services as *not shared* when the service itself is normally shared.
