### ISSUE TITLE
Delegators assigned to Abstract Factories

### ISSUE THREAD

**Issue by TomHAnderson** [zendframework/zend-servicemanager#162]
https://github.com/zendframework/zend-servicemanager/blob/master/src/ServiceManager.php#L744

In the latest version of zend-servicemanager and in the 2.4+ series you cannot assign a delegator to all services created by an abstract factory.  For example in zfcampus/zf-apigility-doctrine all hydrators are created by a single abstract factory.  I want to add default hydration strategies to each hydrator.  To do this I must [manually assign each hydrator to my delegator factory](http://blog.tomhanderson.com/2016/09/doctrine-hydrator-delegator-factories.html).

I think is only makes sense to assign delegators to abstract factories and if the the zendframework/zend-servicemanager team agrees I'll be happy to put in a PR.

**Comment by svycka** [comment]
Also maybe with this would be possible use lazy_services and abstract_factories together.

Example would be log service created by `Zend\Log\LoggerAbstractServiceFactory` could be not created until it actually used.

**Comment by weierophinney** [comment]
Can you please provide an example of configuration, and indicate what you expect to happen, versus what is currently happening? I'm not quite sure I understand, even from your linked blog post.

**Comment by weierophinney** [comment]
Also, why not just extend the abstract factory to do this instead, if you want it to happen for every service the abstract factory manages?

**Comment by TomHAnderson** [comment]
What I'm trying to do is assign delegators to all instances created by an abstract factory. 
I thought that assigning delegators to factories should be done outside the factory.  So in the same way I can assign delegators to other factories I wanted to assign them to an abstract factory.

Since writing this I've moved away from this strategy.  I was trying to attach a Doctrine listener to see if a field existed and, if it did, auto-populate the value.  I can't defend this issue because I worked around it, then removed my strategy.

**Comment by weierophinney** [comment]
I've been thinking on this, and the way delegator factories currently work is very service-specific; we'd essentially need an _additional_ concept, either for purposes of abstract factories or for all services that fulfill a specific criteria. And that adds more complexity for users to understand. If the idea is to add delegators for every service a specific abstract factory can handle, then the abstract factory... should just do the work the delegators would do from the outset, particularly as abstract factories are the path of _most_ resistance (i.e., least performant) when fetching services.

In the case of an abstract factory already existing, the path is to extend the original abstract factory, add the logic before or after a `parent::__invoke()` call, and register the abstract factory extension instead of the original.
