### ISSUE TITLE
zend-servicemanager/src/ServiceManager.php:322

### ISSUE THREAD

**Issue by HardRock88** [zendframework/zend-servicemanager#192]
Hi I found problem in file:
zend-servicemanager/src/ServiceManager.php:322

Current code:
`            $factories = $this->createFactoriesForInvokables($config['invokables']);
`
but I think it should be 
`            $factories = $this->createFactoriesForInvokables($config['factories']);
`
otherwise it just does not work, it always creates controllers using InvokableFactory and ignoring all settings in module.config.php:
`   
 'controllers' => [
    'invokables' => [
      'index' => Controller\IndexController::class,
    ],
    'factories' => [
       Controller\IndexController::class => Controller\Factory\IndexControllerFactory::class,
    ],
],`

**Comment by Ocramius** [comment]
That needs to be backed by a failing test case

**Comment by weierophinney** [comment]
You're using the invokables configuration incorrectly.

The key is the name, but the value is expected to be the name of a class that is _directly instantiable_; the point of invokables is precisely that behavior. Internally, if the two do not match, we alias the key to the class, and then map the class to an InvokableFactory; otherwise we map the key to an InvokableFactory. This is intentional and _documented_ behavior.

Based on the configuration you present, and the expectations you have, the config you have under "invokables" should be more properly under "aliases", as you are intending to _alias_ "index" to a controller for which you have defined a factory.
