### ISSUE TITLE
BC Change not documented 

### ISSUE THREAD

**Issue by reinfi** [zendframework/zend-servicemanager#207]
Hi,

may be I'm missing something, but while I was migrating from zend 2 to zend 3 I stumpled across a not documented BC change.

I used a delegator factory to set labels for form elements base on their name.
This was working fine in zend 2 because the initializer (which calls the init method on form/fieldset classes) was called before the delegator factory returns its instance.

Now this has change as the delegator factory returns the instance and later on calls the initializer to init the form.

Is this expected?

**Comment by weierophinney** [comment]
It is, and it's a case where we did not document it well.

The reason is: we want to operate on the _final instance_ returned from delegation (delegators can return a different instance than the original factory produced). If we run initializers prior to that, it's possible that a _different_ instance will be returned entirely, and the initializers will then have been ignored entirely, which is both problematic from a usage perspective (you expected them to run, but they weren't run on the actual instance returned), as well as from a performance perspective (we've executed initializers whose operations are now being ignored).

Basically, you're relying on a bug in behavior.

What I'd likely do is create an abstract factory for your forms that does the following:

- pulls the form element manager
- pulls the form requested from the form element manager
- returns that form

Then register this factory _with your application service manager_, and register your delegators there. This will ensure the delegators operate on the fully initialized form.

Alternately, instead of using delegators, do the work of the delegators in that same factory.

One benefit to this is that once you migrate to v3, you can register the abstract factory as a _regular factory_ with the service manager, assigning it to the name of each form you want to retrieve using it.

If you adopt this approach using v2, you should be able to upgrade to v3 without issue.

Let me know how that works, and then we can collaborate on a write-up for the documentation.

**Comment by reinfi** [comment]
All your suggestions are not working in my case because the form elements are added within the init method which is called by an initializer registered within the form element manager.

So at this point there is no functionality to do an action which requires the initializer to run. I haven't found anything about initializers to use them with a priority. (Beside that I do not want to use an initializer).

So I think I will need to use a service which I call after every form retrieval to automatically set my labels. Or do you have any other suggestions?

**Comment by reinfi** [comment]
I "solved" the problem now with a listener on the render event, which checks every variable if it is a form and then sets the label. I did not found any other solution which is generic as before.
