### ISSUE TITLE
BUG or INTENTION: ServiceManager::has() does not consider delegators and lazy services!

### ISSUE THREAD

**Issue by fhein** [zendframework/zend-servicemanager#228]
I consider this a bug. But because it's so obvious, it may be intention.
I could fix that. Please advice.

**Comment by Ocramius** [comment]
This is intentional:

 * Lazy services are just a special kind of delegator
 * Delegators can only work if a real service is defined

**Comment by Ocramius** [comment]
May be worth adding a scenario that solidifies this assumption.

On 16 Jan 2018 07:12, "Marco Pivetta" <ocramius@gmail.com> wrote:

This is intentional:

 * Lazy services are just a special kind of delegator
 * Delegators can only work if a real service is defined

**Comment by fhein** [comment]
Factories only work, if they are invokable. This is checked when requested also. Isn't that similar to delegators?

**Comment by Ocramius** [comment]
A factory is supposed to instantiate a service (the assumption is "factory
exists, therefore service exists"), but delegators only map over previous
service definitions, so the service is not guaranteed to exist without a
factory, abstract factory or alias already existing.

**Comment by fhein** [comment]
It is not checked that a factory is able to create a service currently. The answer (`true`) you might get from has() does not grant that you can actually successfully get() that item. Does that behaviour conform to PSR-11? 

I find it difficult for me to understand, what the difference is. A factory key relies on a proper factory config. A delegator key relies on a proper delegator key definition (which again relies on properly defined factories). They both have to assume, because nothing is checked at configuration time.

Two possible solutions: Accept the current state and check delegates also (in has()). This would be for consistency (with factories).  Or: Check at configuration time, whether the supplied factories and delegators are valid enough specified to grant that people can get() the ServiceManager announces to have (has()).

Alternative: Discard has(). :)

IIRC, parameter checks once where part of ServiceManager. 

Please advice.

**Comment by Ocramius** [comment]
This was discussed multiple times in container-interop and in psr-11, as
well as previously here in the ServiceManager component issues (probably
zf2 at the time).

The intent of `has()` is to report whether the container knows and predicts
to be able to instantiate a service. `get()` may still fail due to I/O or
misconfiguration.

An example could be:

 * A db connection that is configured, yet cannot be established due to
network failure
 * A service that depends upon other services that aren't mapped (some
contains can prevent this via static analysis, bit with other complexity
and/or performance issues)


On 23 Jan 2018 07:19, "Frank Hein" <notifications@github.com> wrote:

It is not checked that a factory is able to create a service currently. The
answer (true) you might get from has() does not grant that you can actually
successfully get() that item. Does that behaviour conform to PSR-11?

I find it difficult for me to understand, what the difference is. A factory
key relies on a proper factory config. A delegator key relies on a proper
delegator key definition (which again relies on properly defined
factories). They both have to assume, because nothing is checked at
configuration time.

Two possible solutions: Accept the current state and check delegates also
(in has()). This would be for consistency (with factories). Or: Check at
configuration time, whether the supplied factories and delegators are valid
enough specified to grant that people can get() the ServiceManager
announces to have (has()).

Alternative: Discard has(). :)

IIRC, parameter checks once where part of ServiceManager.

Please advice.

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/zendframework/zend-servicemanager/issues/228#issuecomment-359687953>,
or mute the thread

**Comment by fhein** [comment]
Ok. So sm doesn't predict to have a delegator?

**Comment by Ocramius** [comment]
No, that's really just decoration happening during service creation.

**Comment by fhein** [comment]
F***, of course you are right. That was a stupid one. RTFM. Sorry ...
