### ISSUE TITLE
Tests seem to be not complete

### ISSUE THREAD

**Issue by fhein** [zendframework/zend-servicemanager#235]
I got aware of this issue, when I created a feature branch, applied some changes, ran the tests witch result OK. Then I ran the benchmarks and I got errors not related to phpbench but related to the ServiceManager.

Tracking this down I found, that the benchmarks do things that are not tested by phpunit. Example: `get()` the same service twice. Or `build()` a service, then `get()` the same service. Or `has()` a service, then `get()` it. Just to mention the trivial cases.

ServiceManager can (and probably will) change state when any of this APIs (`build()`,`get()`, `has()`) gets called. There are no tests present to cover that state changes. Not completely true, there are some, but their intention is not to track the state changes. But fortunately they do.

What to do? I hope, this one is important enough and far enough away from any politics, ambitions and such stuff, that we can talk about what to do and who will do it. From my perspective, this would be a team approach.

Some of the present tests are redundant, also. I do not provide examples, because that usually happens on a long term approach. From time to time somebody should review the test suite and eliminate such historical artifacts. To do this would be another task to assign.

Conclusion: Currently it does not mean much when the tests pass.

**Comment by Ocramius** [comment]
Just send in the test additions?

The tests are only as complete as people contributing to the project can
make them be. These are likely simply missed scenarios that should be
covered.

One big and required addition, in my opinion, is mutation testing. Adding
mutation testing would immediately expose incomplete or leaky tests.

**Comment by fhein** [comment]
Do I get you right? Are you just delegating this issue back to me? What, in particular, are the tasks of a maintainer?

Slowly but surely I get a bit disappointed. Maybe, that's my thing. As said in discussions before, PHP open source is not my daily business.

Is my understanding right? People who raise issues are thrown back to them? While important people talk about what feature to deprecate next? Ignoring or disregarding thoughtful concepts of those who did former work? Without even having made the attempt to exploit and optimize what was given?

You are a maintainer of this library, Is there a list of ongoing tasks assigned to that role? I hope so, allthough it does not seem so.

New concept => fame! Maintain and develop what you have => nothing

Is that the pattern?

I am here because 880 microseconds (benchmark on my machine) to initialize a sm are ridiculous. PHP malus considered already. I don't care about your business. My business are real customers.

As a maintainer couldn't you simply say things like: 'Hey guys, I get requests to introduce new things more than I can handle. But we are sitting on a bag of concepts from people before us. Thoughtful concepts. And I have the strong feeling, that we did not manage to exploit those to the bone yet. So,  please, make this beast as fast as possible based on current concepts. Introduce new concepts after this is done.'

Wouldn't that be possible? And appropriate?

Without communication it is definitely not my task, to close gaps I did not open. I wanted to be sure, that you are aware of the quality of the current test environment. Now it's up to you. Are you a maintainer of this library?  

Conclusion: I currently would not take passing tests as an indicator to decide about acceptance  of a pull request.

**Comment by Ocramius** [comment]
Do I get you right? Are you just delegating this issue back to me?

Yes, why not? I get ~35 new issues a day if you consider all the
repositories I work on. Even processing 10% of those is far from realistic.

What, in particular, are the tasks of a maintainer?

Currently, working my ass off to bring my pay back home on client work. I'm
mostly answering from the phone when I find a gap of time.

Slowly but surely I get a bit disappointed. Maybe, that's my thing. As said
in discussions before, PHP open source is not my daily business.

Neither mine: it is my free time that I invest in OSS. If you came for the
money, OSS is rarely a source of money, and rather just a way to create a
portfolio over many sleepless nights.

Is my understanding right? People who raise issues are thrown back to them?

Yes, mostly true. People experiencing an issue in first place also have a
better understanding of the problem, so they are the best fit for bringing
things forward. In more than half of the cases, I personally do assign
issues back to the reporter to get a descriptive test case to be written,
demonstrating the issue they are currently describing in a worse and
misinterpretation-prone DSL (the English language, usually).

While important people talk about what feature to deprecate next? Ignoring
or disregarding thoughtful concepts of those who did former work? Without
even having made the attempt to exploit and optimize what was given?


We do what we can, with the time we're finding to do it. We do bring
forward improvements, removals, deprecations and ideas and take decisions
as "important people" (what a sad label) because we do support everyone
using the tools (literally go out there and answer questions in
chats/forums/conferences/workshops/etc), we collect feedback, we discuss
with dozens other contributors like you and form a long-term and wider view
of the topic, not because we're just being pretentious jerks.

You are a maintainer of this library, Is there a list of ongoing tasks
assigned to that role? I hope so, allthough it does not seem so.

I am one of the maintainers of this library, yes. Most of what I get to do
lately is to respond to people that either need an introduction to how OSS
works, or provide direction about implementation or debugging.

New concept => fame! Maintain and develop what you have => nothing

I do get "fame" mostly from supporting others in projects. You still can't
eat "fame".

Is that the pattern?

No, the pattern is mostly doing all I can in my little free time, and that
also involves delegating what I cannot pursue, if I even get to answer.

I am here because 880 microseconds (benchmark on my machine) to initialize
a sm are ridiculous. PHP malus considered already. I don't care about your
business. My business are real customers.

My real customers are not people like you either. My customers are mostly
people that don't even know what PHP is.

As a maintainer couldn't you simply say things like: 'Hey guys, I get
requests to introduce new things more than I can handle. But we are sitting
on a bag of concepts from people before us. Thoughtful concepts. And I have
the strong feeling, that we did not manage to exploit those to the bone
yet. So, please, make this beast as fast as possible based on current
concepts. Introduce new concepts after this is done.'

How did you jump from "there are holes in the test suite" to this? No, many
concepts from previous implementors can also be plain wrong.

Without communication it is definitely not my task, to close gaps I did not
open. I wanted to be sure, that you are aware of the quality of the current
test environment. Now it's up to you. Are you a maintainer of this library?

No, it is up to the next contributor having time. Sometimes that
contributor is a maintainer.
As a maintainer, this library is stable, working and not requiring
immediate care, security issue fixing or bug-fixing. In fact, the additions
done recently rather increase the chance of regressions for marginal
improvements compared to the pile of other bug reports that are currently
causing real trouble elsewhere (doctrine/orm, zendframework/validator,
zendframework/expressive, zendframework/stratigility,
zendframework/zend-cache and dozens of others)

Conclusion: I currently would not take passing tests as an indicator to
decide about acceptance of a pull request.

There is always a risk in accepting new patches. This library has decent
test coverage, large user-base (kinda acting as "tested on the field),
decent test mutation score, code style, continuous integration and a lot of
people looking over new patches, even if not everyone comments. Heck, good
luck finding "real world" projects that go this far.

If you think something needs improving, by all means do provide those
improvements, because in OSS you cannot *expect* that somebody else will do
it for you, unless they are paid to do so.

To add to it, I to reply to you about this because:
 * My train is late and I'm on the train station platform waiting with
nothing better to do and no way to use my laptop
 * You evidently do not understand how free and open source software is
developed, nor that it is mostly developed by volunteers, which is
perfectly fine

I do wish you to get to maintain many many free projects in the future, so
that you may understand my point of view.

**Comment by Ocramius** [comment]
> Do I get you right? Are you just delegating this issue back to me?

Yes, why not? I get ~35 new issues a day if you consider all the
repositories I work on. Even processing 10% of those is far from realistic.

> What, in particular, are the tasks of a maintainer?

Currently, working my ass off to bring my pay back home on client work. I'm
mostly answering from the phone when I find a gap of time.

> Slowly but surely I get a bit disappointed. Maybe, that's my thing. As said in discussions before, PHP open source is not my daily business.

Neither mine: it is my free time that I invest in OSS. If you came for the
money, OSS is rarely a source of money, and rather just a way to create a
portfolio over many sleepless nights.

> Is my understanding right? People who raise issues are thrown back to them?

Yes, mostly true. People experiencing an issue in first place also have a
better understanding of the problem, so they are the best fit for bringing
things forward. In more than half of the cases, I personally do assign
issues back to the reporter to get a descriptive test case to be written,
demonstrating the issue they are currently describing in a worse and
misinterpretation-prone DSL (the English language, usually).

> While important people talk about what feature to deprecate next? Ignoring or disregarding thoughtful concepts of those who did former work? Without even having made the attempt to exploit and optimize what was given?


We do what we can, with the time we're finding to do it. We do bring
forward improvements, removals, deprecations and ideas and take decisions
as "important people" (what a sad label) because we do support everyone
using the tools (literally go out there and answer questions in
chats/forums/conferences/workshops/etc), we collect feedback, we discuss
with dozens other contributors like you and form a long-term and wider view
of the topic, not because we're just being pretentious jerks.

> You are a maintainer of this library, Is there a list of ongoing tasks assigned to that role? I hope so, allthough it does not seem so.

I am one of the maintainers of this library, yes. Most of what I get to do
lately is to respond to people that either need an introduction to how OSS
works, or provide direction about implementation or debugging.

> New concept => fame! Maintain and develop what you have => nothing

I do get "fame" mostly from supporting others in projects. You still can't
eat "fame".

> Is that the pattern?

No, the pattern is mostly doing all I can in my little free time, and that also involves delegating what I cannot pursue, if I even get to answer.

> I am here because 880 microseconds (benchmark on my machine) to initialize a sm are ridiculous. PHP malus considered already. I don't care about your business. My business are real customers.

My real customers are not people like you either. My customers are mostly
people that don't even know what PHP is.

> As a maintainer couldn't you simply say things like: 'Hey guys, I get requests to introduce new things more than I can handle. But we are sitting on a bag of concepts from people before us. Thoughtful concepts. And I have the strong feeling, that we did not manage to exploit those to the bone yet. So, please, make this beast as fast as possible based on current concepts. Introduce new concepts after this is done.'

How did you jump from "there are holes in the test suite" to this? No, many
concepts from previous implementors can also be plain wrong.

> Without communication it is definitely not my task, to close gaps I did not open. I wanted to be sure, that you are aware of the quality of the current test environment. Now it's up to you. Are you a maintainer of this library?

No, it is up to the next contributor having time. Sometimes that
contributor is a maintainer.
As a maintainer, this library is stable, working and not requiring
immediate care, security issue fixing or bug-fixing. In fact, the additions
done recently rather increase the chance of regressions for marginal
improvements compared to the pile of other bug reports that are currently
causing real trouble elsewhere (doctrine/orm, zendframework/validator,
zendframework/expressive, zendframework/stratigility,
zendframework/zend-cache and dozens of others)

> Conclusion: I currently would not take passing tests as an indicator to decide about acceptance of a pull request.

There is always a risk in accepting new patches. This library has decent
test coverage, large user-base (kinda acting as "tested on the field),
decent test mutation score, code style, continuous integration and a lot of
people looking over new patches, even if not everyone comments. Heck, good
luck finding "real world" projects that go this far.

If you think something needs improving, by all means do provide those
improvements, because in OSS you cannot *expect* that somebody else will do
it for you, unless they are paid to do so.

To add to it, I to reply to you about this because:
 * My train is late and I'm on the train station platform waiting with
nothing better to do and no way to use my laptop
 * You evidently do not understand how free and open source software is
developed, nor that it is mostly developed by volunteers, which is
perfectly fine

I do wish you to get to maintain many many free projects in the future, so
that you may understand my point of view.

Note: re-submitted the comment because writing a frikken blockquote in github requires a degree in vogonics.

**Comment by Ocramius** [comment]
Closing here - topic is widely hijacked. Moved what has to be kept: https://github.com/zendframework/zend-servicemanager/issues/236
