### ISSUE TITLE
Request for discussion: Priority of merges to master

### ISSUE THREAD

**Issue by fhein** [zendframework/zend-servicemanager#246]
Currently, bug fixes are merged to master early. There are bugs, but as long as nobody suffers and complains, IMO to fix them does not need that high priority. Those bugs in most cases do not even come to play, because that would require an edge case configuration. Those are rare, I think.

Several people including me think, that one of the most important things for a ground laying component like ServiceManager is performance. That important, that bad performance is seen as a bug. So enhancements here will often get recognized as a bug fix, IMO.

I suggest to rethink, what changes qualify for a quick deployment to master. Would do you think about that?

**Comment by Ocramius** [comment]
Bug-fixing only on master, everything else goes to develop, no exclusions.

Improvements, whilst welcome, do always go to minor/major as per SemVer,
which we adhere as closely as possible.

**Comment by fhein** [comment]
Thanks. This versioning scheme is good practice.

I don't think, that there is urgency to apply #242 for the bug fixes, because those bugs seem to be not critical in the field. Otherwise there would be loud complains. 

That brought me to question the classification scheme (i.e. not the versioning scheme). There seem to twilight zone, where it is difficult to say, if something should be classified as a bug or as an enhancement.

Imagine, ServiceManager's get() would take 10 minutes to return a service. This would be considered as a bug, I believe. Allthough it could be seen as an enhancement also.

On the other end of the scale is a bugfix for abstract factories defined via members. Allthough this is a bug definitely, it could be treated like an enhancement (or nice to have bugfix), because nobody defines abstract factories via member obviously.

**Comment by weierophinney** [comment]
@fhein Again, if a performance regression is reported due to previous changes in code within the same minor release, we'd consider a performance bugfix. Otherwise, performance improvements are generally _features_ for minor releases.

Generally speaking, bugfixes are the result of reported _unexpected_ behavior; features and enhancements are improvements that present _new_ behavior. _Improved performance_ is a _new feature_ generally, unless it is a by-product of a bugfix.

I'd argue #242 is in fact a bugfix, and there are examples of pre-configured service managers in many components: specifically, any _plugin manager_. The bugfix is primarily around the aspect of properly resolving pre-configured service mappings; the performance improvement is a side-effect.

**Comment by fhein** [comment]
Agreed. In that particular case performance is a side-effect. And in general performance improvements are features (allthough I still believe, that a 10 min get() would be considered to be a bug ;).

I close that now. Thank you! :+1:
