### ISSUE TITLE
BC Break: zend-hydrator does not work with zend-servicemanager 2.7.4 anymore

### ISSUE THREAD

**Issue by BreiteSeite** [zendframework/zend-servicemanager#85]
Hi,

after upgrading `zendframework/zend-servicemanager` from 2.6.0 to 2.7.4 i get the following exception when trying to retrieve `delegatinghydrator` (`Zend\Hydrator\DelegatingHydrator`):

    Uncaught exception 'Zend\\ServiceManager\\Exception\\ServiceNotFoundException' with message 'An alias "Zend\\Hydrator\\DelegatingHydrator" was requested but no service could be found.'

**Comment by svycka** [comment]
should work when merged https://github.com/zendframework/zend-hydrator/pull/11 there are more issues like this with other components, few months ago I created some PR's but none of them got merged not sure why :D
zendframework/zend-validator#45
zendframework/zend-filter#13
zendframework/zend-paginator#7
zendframework/zend-hydrator#11

**Comment by BreiteSeite** [comment]
@svycka great. thanks for the effort of your PRs and communicating them in this issue. Hope they get more attention now.

**Comment by weierophinney** [comment]
@svycka We just started running into these while prepping various components to work with both v2 and v3. One note: we need factory entries both with the canonicalized name **and** the FQCN to ensure forwards compat with v3; can you please update your PRs to do so?

**Comment by kynx** [comment]
@weierophinney For plugin managers I don't think the canonicalized FQCN is enough. In the error above it's the alias that's not resolving? See my last on #81.

**Comment by weierophinney** [comment]
@kynx — see zendframework/zend-serializer#11 — we ran into the issue there, and essentially determined that in v2, the alias target is getting canonicalized in order to perform the factory lookup, while the non-canonicalized alias target is still passed to the `$requestedName` argument, which is why the approach works. We have to have the FQCN + canonicalized versions listed, however, as v3 will use the FQCN entry, while v2 will use the canonicalized one.

**Comment by BreiteSeite** [comment]
As the issues linked from @svycka are already merged/closed i gonna close this issue.

Thank you.
